export const SET_LOADING = 'SET_LOADING';
export const SET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const ADD_CATEGORY = 'CREATE_CATEGORY';

export const SET_STORE_LOADING = 'SET_STORE_LOADING';
export const SET_STORE_ERROR = 'SET_STORE_ERROR';
export const SET_STORE_IS_SUCCESS = 'SET_STORE_IS_SUCCESS';

export const SET_DELETE_LOADING = 'SET_DELETE_LOADING';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SET_DELETE_IS_SUCCESS = 'SET_DELETE_IS_SUCCESS';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const SET_DELETE_ERROR = 'SET_DELETE_ERROR';

export const SET_CATEGORY_TO_UPDATE = 'SET_CATEGORY_TO_UPDATE';
export const SET_UPDATE_LOADING = 'SET_UPDATE_LOADING';
export const SET_UPDATE_ERROR = 'SET-SET_UPDATE_ERROR';
export const SET_UPDATE_IS_SUCCESS = 'SET_UPDATE_IS_SUCCESS';

export const UPDATE_CATEGORY_STATE = 'UPDATE_CATEGORY_STATE';
export const SET_UPDATING_STATE = 'SET_UPDATING_STATE';

export const RESET_STORE_STATE = 'RESET_STORE_STATE';
export const SET_RELOAD = 'SET_RELOAD';
