import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import Layout from 'components/Layouts/AppLayout';
import { ICategoryHome, IHomeResponse } from 'store/reducers/interfaces';
import CategoryList from 'components/Home/CategoryList';
import ProductDrawer from 'components/Home/ProductDrawer';

export const getServerSideProps: GetServerSideProps = async () => {
  const api = process.env.NEXT_PUBLIC_URL_API;
  const categories: ICategoryHome[] = [];

  try {
    const categoryRes = await fetch(`${api}/home`);
    const { ok, categories: data }: IHomeResponse = await categoryRes.json();
    if (ok) {
      categories.push(...data);
    }
  } catch (error) {
    // eslint-disable-next-line no-console
    console.log(error);
  }

  return {
    props: {
      categories,
    },
  };
};

interface Props {
  categories: ICategoryHome[];
}

const Home: NextPage<Props> = ({ categories }: Props) => (
  <Layout title="Home">
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <CategoryList categories={categories} />
      <ProductDrawer />
    </div>
  </Layout>
);
export default Home;
